AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM CloudFormation template"

Resources:
  MyIAMUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "HannaCFN"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
